bot:
  name: sentinel
  servers:
    freenode:
      address: irc.freenode.org
      name: Freenode
      channels:
        - '##security'
        - '##networking'
        - '#owasp'
        - '#archlinux-security'
        - '#oss-security'
